services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=footballManager
      - POSTGRES_USER=footballManager
      - POSTGRES_DB=footballManager
    networks:
      - postgres
  footmallmanager:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=farmtrade
      - DB_USER=farmtrade
      - DB_PASSWORD=farmtrade
      - DB_PORT=5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge